/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnoCSSIconButton: typeof import('./../src/components/Icon/UnoCSSIconButton.vue')['default']
    ZButton: typeof import('./../src/components/ZButton/index.vue')['default']
    ZModal: typeof import('./../src/components/ZModal/index.vue')['default']
    ZSelect: typeof import('./../src/components/ZSelect/index.vue')['default']
    ZToast: typeof import('./../src/components/ZToast/index.vue')['default']
  }
}
